const csrfKey="madar-admin-csrf";let csrf=sessionStorage.getItem(csrfKey)||"";let dashboard=null;
const esc=(v)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const ar=(v)=>Number(v||0).toLocaleString("ar-SA",{maximumFractionDigits:1});
const date=(v)=>v?new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(String(v).replace(" ","T"))):"—";
async function api(path,options={}){const method=(options.method||"GET").toUpperCase();const response=await fetch(`/api/admin${path}`,{...options,headers:{...(options.body?{"Content-Type":"application/json"}:{}),...(method!=="GET"&&csrf?{"X-CSRF-Token":csrf}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(response.status===401){location.href="/login.html?role=staff";throw new Error("انتهت الجلسة")};if(!response.ok)throw new Error(data.error||"تعذّر تحميل البيانات");if(data.csrfToken){csrf=data.csrfToken;sessionStorage.setItem(csrfKey,csrf)}return data}
function summaryCard(label,value){return `<article class="summary-card"><span>${label}</span><strong>${esc(ar(value))}</strong></article>`}
function renderRisk(items,query=""){const filtered=items.filter(r=>`${r.name} ${r.class_name} ${r.teacher_name}`.toLowerCase().includes(query.toLowerCase()));document.getElementById("riskTable").innerHTML=`<div class="table-wrap"><table><thead><tr><th>الطالبة</th><th>الفصل</th><th>المعلمة</th><th>التقدم</th></tr></thead><tbody>${filtered.length?filtered.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.class_name)}</td><td>${esc(r.teacher_name)}</td><td><span class="status ${Number(r.progress_percent)<40?"danger":""}">${ar(r.progress_percent)}٪</span></td></tr>`).join(""):`<tr><td colspan="4">لا توجد نتائج.</td></tr>`}</tbody></table></div>`}
function render(data){dashboard=data;const s=data.summary;document.getElementById("adminSummary").innerHTML=[summaryCard("المعلمات",s.teachers),summaryCard("الطالبات",s.students),summaryCard("أولياء الأمور",s.parents),summaryCard("الاختبارات المنشورة",s.publishedTests),summaryCard("طلبات المعلمات",s.pendingTeachers),summaryCard("طلبات أولياء الأمور",s.pendingParents)].join("");renderRisk(data.atRisk||[]);document.getElementById("classTable").innerHTML=`<div class="table-wrap"><table><thead><tr><th>الفصل</th><th>المعلمة</th><th>الطالبات</th><th>التقدم</th></tr></thead><tbody>${(data.classes||[]).map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.teacher_name)}</td><td>${ar(r.students)}</td><td><div class="progress-bar"><i style="width:${Math.max(0,Math.min(100,Number(r.progress||0)))}%"></i></div><small>${ar(r.progress)}٪</small></td></tr>`).join("")}</tbody></table></div>`;document.getElementById("testTable").innerHTML=`<div class="table-wrap"><table><thead><tr><th>الاختبار</th><th>المعلمة</th><th>الفصل</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>${(data.recentTests||[]).map(r=>`<tr><td>${esc(r.title)}</td><td>${esc(r.teacher_name)}</td><td>${esc(r.class_name||"—")}</td><td><span class="status">${esc(r.status)}</span></td><td>${date(r.created_at)}</td></tr>`).join("")}</tbody></table></div>`;document.getElementById("activityTable").innerHTML=`<div class="table-wrap"><table><thead><tr><th>الدور</th><th>العملية</th><th>التفاصيل</th><th>التاريخ</th></tr></thead><tbody>${(data.activity||[]).map(r=>`<tr><td>${esc(r.actor_role)}</td><td>${esc(r.action)}</td><td>${esc(r.details||"—")}</td><td>${date(r.created_at)}</td></tr>`).join("")}</tbody></table></div>`;window.MadarResponsiveTables?.refresh()}
(async()=>{try{const me=await api("/me");document.getElementById("adminName").textContent=me.name;render(await api("/enhancements/overview"))}catch(error){document.getElementById("adminSummary").innerHTML=`<div>${esc(error.message)}</div>`}})();
document.getElementById("riskSearch").addEventListener("input",e=>renderRisk(dashboard?.atRisk||[],e.target.value));
document.getElementById("adminLogout").onclick=async()=>{const result=await api("/logout",{method:"POST",body:"{}"});sessionStorage.removeItem(csrfKey);location.href=result.previewEnded?(result.redirect||"/owner/dashboard"):"/login.html?role=staff"};
